name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Deploy to Digital Ocean Droplet via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          password: ${{ secrets.PASSWORD }}
          username: ${{ secrets.USERNAME }}
          
          script: |
            cd digitalocean
            echo 'Changed to digital ocean work directory'
            docker-compose down -v
            echo 'Docker-Compose down'
            git pull origin master
            echo 'Pulled master from github'
            docker-compose build
            echo 'Built new image'
            docker-compose up
            echo 'Image now running'
            
