name: CI


# Controls when the workflow will run
on:
  push:
    branches: [ master ]

# Actions
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Deploy to Digital Ocean Droplet via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          password: ${{ secrets.PASSWORD }}
          username: ${{ secrets.USERNAME }}
          script:
            # Move to work directory
            cd digitalocean
            
            # Stop and remove containers
            docker-compose down -v
            
            # Get new master branch
            git pull origin master
            
            docker-compose build
            
            docker-compose up
            
